### ISSUE TITLE
Installation issues with Python3.8

### ISSUE THREAD

**Issue by j-andrews7** [GuidoBartoli/sherloq#10]
Just a heads up, there is a requirement issue with python3.8, as `Tensorflow==1.15.3` is not supported. Well, `Tensorflow < 2` isn't supported on python 3.8. May be worth a note in the README for others who run into the same issue. Downgrading to python 3.7 works fine.

**Comment by j-andrews7** [comment]
Also can confirm it works through WSL with and Xdisplay properly set up (MobaXterm, Xming, etc).

**Comment by GuidoBartoli** [comment]
Thanks, it should be fixed in latest 9fbeb713f837a9468d893049bf3ba4d713791b54 commit, please check it out.
