### ISSUE TITLE
Feature Request: Masking for Copy-Move Forgery Tool

### ISSUE THREAD

**Issue by j-andrews7** [GuidoBartoli/sherloq#11]
Blatant feature request here. The ability to mask certain areas from being processed by the CMF tool would be wonderful. I am trying to use it for detecting image duplication in published articles (it's performing quite well!), and text in the figures result in a lot of noise. Being able to mask them within the program rather than editing beforehand would be very nice.

**Comment by GuidoBartoli** [comment]
Nice suggestion, I added it to the [New features](https://github.com/GuidoBartoli/sherloq/projects/2) list, thanks!

**Comment by GuidoBartoli** [comment]
Latest commit 7a9372288d92e8ff57561474a15a6e15813cf5eb added the ability to load an image to be used as a mask to filter keypoints (black = ignored regions).
It is a bit basic, but it should do the trick... ;)

**Comment by j-andrews7** [comment]
Ah, so this still requires editing of the original image beforehand, in which case I might as well just delete or mask the text manually. I can see where this would still be useful. 

My hope was that within the program, we'd be able to select the region(s) to be masked on the fly. Almost certainly a lot more challenging to implement, but would be nifty!

**Comment by GuidoBartoli** [comment]
At the moment, you have to duplicate the original image, paint black on the masked areas (you can use Paint or GIMP) and load the mask (everything different from pure black will be analyzed).
Direct painting inside Sherloq is not easy, but it’s still on the roadmap ;)

**Comment by j-andrews7** [comment]
Excellent, glad to hear it.

**Comment by under-score** [comment]
> At the moment, you have to duplicate the original image, paint black on the masked areas (you can use Paint or GIMP) and load the mask (everything different from pure black will be analyzed).
> Direct painting inside Sherloq is definitely not easy, but still on the roadmap ;)

For the records - there is some code at https://www.youtube.com/watch?v=qEgyGyVA1ZQ
