### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by darkcracker** [GuidoBartoli/sherloq#2]
downloaded the file. unable to install. using kali 2020.2. need instructions. do i have to compile first?

**Comment by Lazza** [comment]
The author's description seems pretty detailed on this point:

> Even if the project objective is clear, actually **the software is an early prototype, so some functionalities are still missing (see list above) and it can be run only from Qt Creator under Linux.** I put it on Github to track my development progress even during the alpha stage, so expect issues, bugs and installation headaches, however, if you want to take a look around, feel free to contact me if you are experiencing problems in making it run.

**Comment by GuidoBartoli** [comment]
Hi @darkcracker, sorry but I never tested it under Kali, only on Linux Mint based on Ubuntu. 

As @Lazza kindly reminded, the software is in development and the good news is that in my spare time I'm porting it to Python + PySide2, so the next iteration will be much easier to install. However, if you have problems with the Qt GUI, you can try to compile the C++ command line version, it just needs OpenCV, Boost and Alglib as reported in the [CmakeLists.txt](https://github.com/GuidoBartoli/sherloq/blob/master/cli/CMakeLists2.txt) file.

**Comment by darkcracker** [comment]
thank you for the clarification and the quick response. will try to compile the c++ command line version as suggested.

**Comment by GuidoBartoli** [comment]
@darkcracker I begun porting code to Python, please check the [latest commit](https://github.com/GuidoBartoli/sherloq/commit/9addac7289dbce1e442e9a00e8e7f4d9138d85d3) and updated README.
