### ISSUE TITLE
[Mac OS] Libmagic missing

### ISSUE THREAD

**Issue by thmsl** [GuidoBartoli/sherloq#23]
On Mac OS Catalina, libmagic cannot be found when launching Sherloq

```
ImportError: failed to find libmagic.  Check your installation
```

Fixed by installing libmagic with brew

```
brew install libmagic
```

**Comment by GuidoBartoli** [comment]
Thanks, I will add a specific `requirements_mac.txt` for MacOs with `libmagic`, too.

**Comment by GuidoBartoli** [comment]
`README` updated with your suggestion, thanks! :+1:
