### ISSUE TITLE
PRNU comparison doesn't work?

### ISSUE THREAD

**Issue by Vlady217** [GuidoBartoli/sherloq#25]
All the functions
 in _italics_ are not working? 
Am I'm missing something?
Thanx
![Capturegfhfgh](https://user-images.githubusercontent.com/76610711/103147906-3c5c9680-4762-11eb-91ff-f27b57b5848c.PNG)

**Comment by GuidoBartoli** [comment]
Yep, those functions are not yet implemented, sorry... I will add them as soon as I will have time! :)
I updated the README to be more clear about this, thanks for reporting it out.
