### ISSUE TITLE
Blink between Original and Processed images

### ISSUE THREAD

**Issue by jtlz2** [GuidoBartoli/sherloq#27]
Sherloq is **amazing** - thank you.

That aside - it would be very useful to have a 'blink' button that automatically toggles between overlaid Original and Processed images for a given operation at a specified or preset time interval. It would help enormously for comparing areas of interest to the original. Does that make sense?

This is borrowed from SAOIMAGE ds9 - https://sites.google.com/cfa.harvard.edu/saoimageds9

There's tonnes of other stuff that could be borrowed - including output of contours/regions of interest into ascii files that can be reloaded/overlaid etc., (x,y) coordinates for mouse, ...

Is there a rotate button anywhere?

Thanks again!

**Comment by GuidoBartoli** [comment]
> Sherloq is **amazing** - thank you.

Many thanks! I'm really happy if it can be of any help in research :smile: :pray: 

> 
> That aside - it would be very useful to have a 'blink' button that automatically toggles between overlaid Original and Processed images for a given operation at a specified or preset time interval. It would help enormously for comparing areas of interest to the original. Does that make sense?
> 
> This is borrowed from SAOIMAGE ds9 - https://sites.google.com/cfa.harvard.edu/saoimageds9
> 
> There's tonnes of other stuff that could be borrowed - including output of contours/regions of interest into ascii files that can be reloaded/overlaid etc., (x,y) coordinates for mouse, ...
> 
> Is there a rotate button anywhere?
> 
> Thanks again!

You can press the space key to quickly toggle between original and processed image inside a window. Did you try it?

**Comment by jtlz2** [comment]
There you go - I didn't realise - perfect - thanks!

**Comment by GuidoBartoli** [comment]
Actually I added that but since the documentation is not yet ready, it is a somewhat hidden feature. Does the interface show this shortcut key when you hover the mouse pointer on the original/processed toggles?

**Comment by jtlz2** [comment]
Not that I can see?

**Comment by GuidoBartoli** [comment]
Ok, I will add it in the toggles tooltip, so it can be seen, thanks.
