### ISSUE TITLE
Features Roadmap

### ISSUE THREAD

**Issue by jtlz2** [GuidoBartoli/sherloq#29]
Is there a roadmap for the "italicized" features, or could there be one?

Thanks!

**Comment by GuidoBartoli** [comment]
Sherloq is a part time project that I can work on only when I have free time from work and family, so unfortunately I'm not able to provide deadlines or forecasts, I am sorry. I develop new features in my spare moments trying as much as possible to also give support to those who encounter difficulties and report them here on Github.
In any case you can take a look at what I've posted in the [Projects](https://github.com/GuidoBartoli/sherloq/projects) section to get an idea of what's still to be done... do you want to give me a hand with Python and OpenCV? :wink:

**Comment by jtlz2** [comment]
@GuidoBartoli I am happy to assist but very wary of overcommitting. Also, huge opportunities for scope creep!

Maybe I could start with something incredibly small to get going. I am keen to work on export options for example.

Perhaps we should take the planning discussion offline (or is that bad form?) - is your email discoverable somewhere?
