### ISSUE TITLE
load_image

### ISSUE THREAD

**Issue by rsj123** [GuidoBartoli/sherloq#3]
Traceback (most recent call last):
  File "sherloq.py", line 218, in load_file
    self.filename, basename, self.image = load_image(self)
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by GuidoBartoli** [comment]
Did you update to the latest repository version? I changed the `load_image()` function in `utility.py` to return also the basename of the file path, maybe you have an old version of it.

**Comment by rsj123** [comment]
wow, it's work for me, Thx!

**Comment by rsj123** [comment]
emm, I just tried to update the code, it is work but it still error while opening some img which with chinese path

**Comment by GuidoBartoli** [comment]
Mmhh maybe `imread()` function from `opencv` does not handle chinese characters well... I'm European, I do not know how to test it, can you please write here a typical path that does not work? However, does it work with normal paths without chinese characters?

**Comment by rsj123** [comment]
just try "新建文件夹", and it work well with normal paths

**Comment by GuidoBartoli** [comment]
I tried loading an image from a folder with that name and it works fine here: 
![chinese](https://user-images.githubusercontent.com/16103676/83028475-c8bea380-a031-11ea-9e61-789bba7eb0ef.jpg)

However, I just committed a new version with the previous loading bug corrected, so please update your working copy and let me know if everything works.

**Comment by rsj123** [comment]
thanks, I use it on windows, might the reasion is the different system
