### ISSUE TITLE
Load image dialogue - macOS

### ISSUE THREAD

**Issue by jtlz2** [GuidoBartoli/sherloq#33]
On macOS all views in the Load image dialogue show icons like "JPEG", "PNG" etc. - is this platform specific and is there a way to make it show thumbnail previews as the system dialogue would?

**Comment by GuidoBartoli** [comment]
To make the dialog work as intended, I had to disable native look and use the Qt rendering of it. I also noticed that under Linux the thumbnails are not shown. Can you try to comment this line in the code and try again?

https://github.com/GuidoBartoli/sherloq/blob/0ce7fe773980e2717270011178e4e396159f31c7/gui/utility.py#L190
