### ISSUE TITLE
Feature Request - support for multiple images open simultaneously

### ISSUE THREAD

**Issue by jtlz2** [GuidoBartoli/sherloq#34]
This would be super useful. Is it straightforward to implement or would it require major architectural changes?

**Comment by GuidoBartoli** [comment]
Well, this is huge... :sweat_smile:
Sherloq already uses a Multi Document Interface (MDI) to show multiple windows for each opened tool, so adding another layer for opening also multiple images would introduce a serious rethinking of the whole architecture and sincerely I do not see a straightforward way to implement it efficiently in Qt.

**Comment by jtlz2** [comment]
I thought so - thanks for the info!
