### ISSUE TITLE
Feature Request - crop image

### ISSUE THREAD

**Issue by jtlz2** [GuidoBartoli/sherloq#35]
@GuidoBartoli Apologies for the plethora of issues.....

A crop operation would be quite useful. This would involve drawing a box on the original image so that all subsequent operations operate on the masked region rather than the whole image. Would that be possible?

**Comment by GuidoBartoli** [comment]
I added it to the roadmap under Projects, thanks for the suggestion!
I think that it could be integrated into the generic Viewer, a dedicated tool under Various is too much...
