### ISSUE TITLE
UX issue

### ISSUE THREAD

**Issue by jtlz2** [GuidoBartoli/sherloq#36]
In Contrast Enhancement, Process runs for all algorithms then the user selects their favourite to display. But in others e.g. Copy-Move Forgery the parameters are set before the Process button is hit. Could these steps easily be made more consistent?

**Comment by GuidoBartoli** [comment]
The two instruments have different philosophies. "Contrast Enhancement", once the block size is set, calculates in one step three maps ("Histogram Error", "Channel Similarity" and "Joint Probability") and a posteriori you can choose which one to display avoiding having to recalculate them all the times.

"Copy-Move Forgery" on the other hand employs several sequential steps to estimate the cloned zones and the parameters affect each of them. When you change one of them Sherloq recalculates only the necessary steps to get the final result and not have to do it all over again.
