### ISSUE TITLE
Geolocation data tool

### ISSUE THREAD

**Issue by Sofurs** [GuidoBartoli/sherloq#38]
No matter what the image is, the geolocation data tool always points to the same place in Boston.
![image](https://user-images.githubusercontent.com/39196903/115390914-21b1a000-a1df-11eb-8440-47785172a78f.png)

**Comment by GuidoBartoli** [comment]
You are right, I can replicate this... there must be a fixed geoposition inside the [HTML code](https://github.com/GuidoBartoli/sherloq/blob/ca726d04c8b927e85ed7d197808bc2ee92be1a60/gui/location.py#L32) I used to embed the map, I will check it out as soon as possible.

Thanks

**Comment by GuidoBartoli** [comment]
Should be fixed in 8330e54551a764d19a4ca611a4152ef48f0fac9f, thanks for reporting!
