### ISSUE TITLE
doesn't start anymore

### ISSUE THREAD

**Issue by under-score** [GuidoBartoli/sherloq#39]
even after updating `requirements.txt` with tensorflow=1.15 and `brew install libmagic` the macOS Big Sur terminal hangs forever showing the warning

```
WARNING:tensorflow:From tilde/.virtualenvs/Sherloq/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating: non-resource variables are not supported in the long term
```

**Comment by GuidoBartoli** [comment]
Well, that's strange, because it's just a tensorflow warning, the application should start anyway. How come you forced the installation of version 1.15? I didn't specify anything in the "requirements.txt" file, because version 2 was fine, since the code uses the compatibility functions of version 1 anyway.

**Comment by under-score** [comment]
oh, 1.15 requirement goes back to out previous conversation - see the end of [https://github.com/GuidoBartoli/sherloq/issues/7](https://github.com/GuidoBartoli/sherloq/issues/7 ) - with the current tensorflow I get the same error message as before. BTW - big thank you - see acknowledgment at [https://www.atsjournals.org/doi/10.1165/rcmb.2020-0419LE](https://www.atsjournals.org/doi/10.1165/rcmb.2020-0419LE)

**Comment by GuidoBartoli** [comment]
Ok, I will take a look at it during weekend, I have a Macbook to try it out.

Many many thanks for citing it in your article, I'm really proud and honored! :blush:

**Comment by under-score** [comment]
deleted all Python related binaries - it works again ;-)

**Comment by GuidoBartoli** [comment]
Good to hear that! :ok_hand:

**Comment by under-score** [comment]
Same issue again a few months later.  
After inserting several print("*1") commands I found out that 4 packages had been missing (packaging, dateutil, wrapt, typing_extensions) for whatever reason.  
Even then the window was frozen without any error message. Another bugreport](https://bugreports.qt.io/browse/PYSIDE-1444) finally helped

```
export QT_MAC_WANTS_LAYER=1
export QT_MAC_USE_NSWINDOW=1
python sherloq.py
```

**Comment by GuidoBartoli** [comment]
Nice, I will add to the README under the Mac section as soon as possible... thanks for reporting it out!
