### ISSUE TITLE
PYSIDE2 error

### ISSUE THREAD

**Issue by C4l1b3r** [GuidoBartoli/sherloq#42]
`Traceback (most recent call last):
  File "/data/data/com.termux/files/home/sherloq/gui/sherloq.py", line 4, in <module>
    from PySide2.QtCore import Qt, QSettings
ModuleNotFoundError: No module named 'PySide2'`

**Comment by GuidoBartoli** [comment]
It seems `PySide2` package is not installed... Did you run `pip install -r requirements.txt`? With the `sq` virtual environment activated, what is the output of `pip list`?
