### ISSUE TITLE
source ~/.bash_profile

### ISSUE THREAD

**Issue by novitae** [GuidoBartoli/sherloq#45]
i am on Mac, I followed the installation instruction, and when I type `source ~/.bash_profile`, I get this :
```
-sh: -e: command not found
-sh: /usr/local/bin/virtualenvwrapper.sh: No such file or directory
```
help please
thanks

**Comment by GuidoBartoli** [comment]
Did you try this?
https://stackoverflow.com/questions/52469116/cannot-run-virtualenvwrapper-on-macos
