### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [GuidoBartoli/sherloq#49]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
lokal$ perl -p -i.orig -0777 -e 's/^(?<indentation>\s+)(?<target>\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+%^@]|-(?!>)|&(?!&)|\|(?!\|)|\*\*?|\/\/?|<<|>>)/$+{indentation}$+{target} $+{operator}=/gm' $(find ~/Projekte/Sherloq/lokal -name '*.py')
```

**Comment by elfring** [comment]
:thought_balloon: Can you follow [the rationale of the Python enhancement proposal 203](https://www.python.org/dev/peps/pep-0203/#rationale "Proposal for augmented assignments") (from 2000-07-13)?

**Comment by GuidoBartoli** [comment]
Sorry, but I do not understand your point on this and I do not see how it can be applied to Sherloq.

**Comment by elfring** [comment]
:eyes: Would you like to take another look at available information to achieve a better understanding?


>… and I do not see how it can be applied to Sherloq.

:crystal_ball: Would you dare to apply a variant of the shown Perl command example on another development repository?
