### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by D1D0code** [GuidoBartoli/sherloq#50]
I got this error from python sherloq.py
Have no error while installing

xxx@xxx:~/sherloq/sherloq/gui$ python sherloq.py 
  File "sherloq.py", line 53
    self.setWindowTitle(f"{QApplication.applicationName()} {QApplication.applicationVersion()}")
                                                                                              ^
SyntaxError: invalid syntax

Any advice, need pre-installed libraries or something more to do?
running
Python 2.7.18
Python 3.8.10

**Comment by GuidoBartoli** [comment]
Sherloq is not compatible with Python 2.7, did you follow [these steps](https://github.com/GuidoBartoli/sherloq#installation) to install it? Which operating system are you using?

**Comment by D1D0code** [comment]
hi
I'm running linux mint last version, yes I copy paste all the steps

**Comment by GuidoBartoli** [comment]
Can you please launch `python` interpreter from the shell and print its output?

**Comment by D1D0code** [comment]
Hi Guido
I just purge / reinstall python
reinstall your tool and it works
Thanks for your interest and your tool
