### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'append'

### ISSUE THREAD

**Issue by tgranqvist** [GuidoBartoli/sherloq#52]
When opening a JPEG file and selecting the channel histogram, the following error occurs;
`Traceback (most recent call last):
  File "C:\Tools\Sherloq\sherloq\gui\sherloq.py", line 349, in open_tool
    tool_widget = HistWidget(self.image)
  File "C:\Tools\Sherloq\sherloq\gui\histogram.py", line 47, in __init__
    channels.append(cv.cvtColor(image, cv.COLOR_BGR2GRAY))
AttributeError: 'tuple' object has no attribute 'append'`

I am on Windows 10 Professional, Python 3.9.6, and Sherloq 0.85a

**Comment by GuidoBartoli** [comment]
Hi, thanks for reporting, I will look into it as soon as possible (I have to review it on a specific Windows machine, currently I am on Linux).

**Comment by chertoGUN** [comment]
in the histogram.py file, you need to find line 46 and change the type like this:

        channels = cv.split(cv.cvtColor(image, cv.COLOR_BGR2RGB))
        channels = list(channels) #fix https://github.com/GuidoBartoli/sherloq/issues/52
        channels.append(cv.cvtColor(image, cv.COLOR_BGR2GRAY))

**Comment by GuidoBartoli** [comment]
Thanks! Does commit c1ef766a7fd46d18f8d42be8091dfdb5babe7719 solve the problem?

**Comment by chertoGUN** [comment]
don't know, i fix like this:

    channels = cv.split(cv.cvtColor(image, cv.COLOR_BGR2RGB))
    channels = list(channels) #fix https://github.com/GuidoBartoli/sherloq/issues/52
    channels.append(cv.cvtColor(image, cv.COLOR_BGR2GRAY))

and it's working now
