### ISSUE TITLE
some tools are in italics and don't work 

### ISSUE THREAD

**Issue by chertoGUN** [GuidoBartoli/sherloq#54]
list:
Illuminant Map 
PRNU Identification 
Multiple Compression 
JPEG Ghost Maps
Image Resampling
Dead\Hot Pixels

**Comment by chertoGUN** [comment]
for Multiple Compression i solved -> 
fix on file "sherloq.py", (you need to uncomment lines 392 and 393)

**Comment by GuidoBartoli** [comment]
As reported in the [README](https://github.com/GuidoBartoli/sherloq#features), the functions with name in italics are planned, but the implementation is yet to be done, sorry.
