### ISSUE TITLE
Bugs in Windows

### ISSUE THREAD

**Issue by marlonio** [GuidoBartoli/sherloq#55]
Hi Guido, i installed on my windows laptop Sherloq. It was no easy because i crush into the "libmagic issue". At the end i solved installing matplotlib with pip. Now i got a serie of bugs when i click on some tools. First, when i start the software from the terminal i got the "error" that you can see in the image: ![cattura](https://user-images.githubusercontent.com/77846722/165913454-cfc9357f-da40-4038-889b-802e06a2ccc4.png)
I'll give you the list of the tools that work and the tools that doesn't work;

1. **File Digest** - _Doesn't work_ (in terminal appear an error "magic.MagicException: None") THIS ERROR DOES NOT CRASH THE SW 
2. **Hex Editor** - _Works well_ 
3. **Similiar Search** - _Works well_  (Could be nice have Yandex Reverse Image Search on the website list..)
4. **Header Structure** - _Doesn't work_ (it's requested the "Enter" pressing inside the terminal, after you did it a windows in SW appear but with "impossible reach the website" info) THIS ERROR DOES NOT CRASH THE SW
5. **EXIF Full Dump** - _Works well_ 
6. **Thumbnail Analysis** - _Works well_  (But it's requested the "Enter" pressing inside the terminal windows"
7. **Geolocation Data** - _Not tested with geolocated picture, but seems to work_ 
8. **Enhancing Magnifier** - _Works well_ 
9. **Cannel Histogram** - _Works well_ 
10. **Global Adjustments** - _Works well_ 
11. **Reference Comparison** - _Works well_ 
12. **Luminance Gradient** - _Works well_ 
13. **Echo Edge Filter** - _Works well_ 
14. **Wavelet Treshold** - _Works well_ 
15. **Frequency Split** - _Works well_ 
16. **PCA Projection** - _Works well_ 
17. **Pixel Statitics** - _Works well_ 
18. **Noise Separation** - _Works well_ 
19. **MinMax Deviation** - _Works well_ 
20. **BitPlane Values** - _Works well_ 
21. **PRNU Identification** - _Doesnt Work_  (Nothing Happen when i press it) THIS ERROR DOES NOT CRASH THE SW 
22. **Quality Esimation** - _Doesnt Work_   THIS ERROR CRASH THE SW  (No info appear in terminal windows)
23. **Error Level Analysis** - _Works well_ 
24. **Multiple Compression** - _Doesnt Work_  (Nothing Happen when i press it) THIS ERROR DOES NOT CRASH THE SW 
25. **Jpeg Ghost Map** - _Doesnt Work_  (Nothing Happen when i press it) THIS ERROR DOES NOT CRASH THE SW 
26. **Contrast Enhancement** - _Works well_ 
27. **CopyMove Forgery** - _Works well_ 
28. **Composite Splicing** - _Works well_ 
29. **Image Resampling** - _Doesnt Work_  (Nothing Happen when i press it) THIS ERROR DOES NOT CRASH THE SW 
30. **Median Filtering** - _Works well_ 
31. **Illuminant Map** - _Doesnt Work_  (Nothing Happen when i press it) THIS ERROR DOES NOT CRASH THE SW 
32. **DeadHot Pixels** - _Doesnt Work_  (Nothing Happen when i press it) THIS ERROR DOES NOT CRASH THE SW 
33. **Stereogram Decoder** - _Works well_ 

I'm really interested in the software, I have not particular computer skills, but if you need i could help you as a tester. Thanks for your work and trust me, is really interesting and if you improve it you could get big satisfaction from it

**Comment by TechiBBB** [comment]
Hi,
I updated the Sherloq source code today and cannot confirm these issues. @marlonio : is it possible that your source code is outdated? The Quality Estimation feature is working fine on my side (see below)
 and the italic menu entries are disabled in my menu, that means nothing happens when I access them (Windows10, Python 3.10.4).
![QE](https://user-images.githubusercontent.com/103127922/165929497-628afd39-8c4d-4a1c-8cf3-66b4e842860b.png)
