### ISSUE TITLE
Error: " *args, **kwargs "

### ISSUE THREAD

**Issue by Griffon67** [GuidoBartoli/sherloq#56]
When running sherloq.py, the following message appears:

> Traceback (most recent call last):
>   File "E:\GitHub\sherloq-master\gui\sherloq.py", line 20, in <module>
>     from histogram import HistWidget
>   File "C:\Users\Griffon\AppData\Local\Programs\Python\Python39\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
>     return original_import(name, *args, **kwargs)
>   File "E:\GitHub\sherloq-master\gui\histogram.py", line 17, in <module>
>     from matplotlib.backends.backend_qt5agg import FigureCanvas
>   File "C:\Users\Griffon\AppData\Local\Programs\Python\Python39\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
>     return original_import(name, *args, **kwargs)
> ModuleNotFoundError: No module named 'matplotlib'

**Comment by GuidoBartoli** [comment]
It seems that you're running the script from inside your `shiboken2` virtual environment... did you install `matplotlib` inside that? You can check it out executing ```pip list``` from the prompt.

**Comment by Griffon67** [comment]
> It seems that you're running the script from inside your `shiboken2` virtual environment... 

Thanks!
