### ISSUE TITLE
No chances to get a Sherloq VM?

### ISSUE THREAD

**Issue by studiogdm** [GuidoBartoli/sherloq#62]
Hi, I tried to install several times Sherloq in both Windows and Linux enviroments without success.
Every time I always get errors. 
So I think would be nice to have a working Sherloq Virtual Machine.
is it avaible?
Thanks for attention

Peppe

**Comment by GuidoBartoli** [comment]
Hi, actually I'm trying to use [Nuitka](https://nuitka.net/) to produce compiled executables for Linux, Windows and MacOS. The first attempt produced a very large (3.5GB) file and I have yet to test, but I will keep you updated about that.

**Comment by GuidoBartoli** [comment]
Unfortunately, the compiled executable gives problems with `xgboost`, because when it is launched it cannot find the necessary dynamic libraries... I think it requires a system-wide installation of `xgboost` to work, I will try in the next few days.
In the meantime, can you tell me what problems you encountered with the installation in a Linux environment? What distribution are you using?

**Comment by studiogdm** [comment]
I tried a new installation on a VM lubuntu 22.x and finally it started!
But I got some warnings (as usual) during the installation and I am not
sure now it is fully working...
Some filters seems to freeze the machine... others simply does nothing.
I attached the installation bash output. If you mind I can send you the
whole VM by wetransfer, let me know.
Thanks in advance.

Peppe


Il giorno sab 8 ott 2022 alle ore 10:21 Guido Bartoli <
***@***.***> ha scritto:

**Comment by studiogdm** [comment]
I also tried a windows installation. Everything gone fine until I gave the command python sherloq.py
Then the GUI didn't start andI got that message:

sq) C:\sherloq-master\gui>python sherloq.py
Traceback (most recent call last):
  File "C:\sherloq-master\gui\sherloq.py", line 12, in <module>
    from digest import DigestWidget
  File "C:\sherloq-master\gui\digest.py", line 5, in <module>
    import magic
  File "C:\Users\tech6\Envs\sq\lib\site-packages\magic\__init__.py", line 209, in <module>
    libmagic = loader.load_lib()
  File "C:\Users\tech6\Envs\sq\lib\site-packages\magic\loader.py", line 49, in load_lib
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation

**Comment by GuidoBartoli** [comment]
Did you install the required packages using `requirements_win.txt` as explained [here](https://github.com/GuidoBartoli/sherloq#22-launch-program)?

**Comment by studiogdm** [comment]
Ok, thank you!
Grazie.

Peppe


Il giorno gio 6 ott 2022 alle ore 18:22 Guido Bartoli <
***@***.***> ha scritto:
