### ISSUE TITLE
Error requirements.txt

### ISSUE THREAD

**Issue by andre-santos1** [GuidoBartoli/sherloq#64]
When I run "pip install -r requirements.txt" I get the following error:

ERROR: Could not find a version that satisfies the requirement pyside6==6.3.2 (from -r requirements.txt (line 8)) (from versions: 6.0.0a1.dev1606911628, 6.0.0, 6.0.1, 6.0.2, 6.0.3, 6.0.4, 6.1.0, 6.1.1, 6.1.2, 6.1.3, 6.2.0, 6.2.1, 6.2.2, 6.2.2.1, 6.2.3, 6.2.4)

ERROR: No matching distribution found for pyside6==6.3.2 (from -r requirements.txt (line 8))

**Comment by GuidoBartoli** [comment]
Are you on Windows or Linux platform?

**Comment by andre-santos1** [comment]
I'm running sherloq on Ubuntu 22.04

**Comment by GuidoBartoli** [comment]
Can you please show the output of the command `$ uname -a` on the Terminal?

**Comment by andre-santos1** [comment]
Sure thing Guido.

uname -a

Linux osint 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by GuidoBartoli** [comment]
Can you try to create a new virtual environment from scratch and install the `pip` requirements from [this file](https://github.com/GuidoBartoli/sherloq/files/10195032/requirements.txt)?

**Comment by andre-santos1** [comment]
Hi Guido! I did that!! Used conda and everything is working like a charm! I appreciate your help!

**Comment by GuidoBartoli** [comment]
Thanks to you for reporting that, fixed in [4332fd9](https://github.com/GuidoBartoli/sherloq/commit/4332fd9c3fd8fa3a229e3403997b566e0e6ff917).
