### ISSUE TITLE
ModuleNotFoundError: No module named 'PySide6'

### ISSUE THREAD

**Issue by DonaldLaborde** [GuidoBartoli/sherloq#70]
Hello and congratulations for creating such a tool !
I'm on LInux and I followed your instructions to install "Sherloq"

Then I used the following command to start the software : `python3 ~/Downloads/Programs/sherloq/gui/sherloq.py`

I got this issue : _
_Traceback (most recent call last):
  File "/home/osint/Downloads/Programs/sherloq/gui/sherloq.py", line 4, in <module>
    from PySide6.QtCore import Qt, QSettings
ModuleNotFoundError: No module named 'PySide6'__

What can I do to fix it please ?

**Comment by GuidoBartoli** [comment]
Hi, can you please report the output of `pip list` from inside the virtual environment?

**Comment by DonaldLaborde** [comment]
Sorry I don't know how to do that , what cmd to I use for ?

**Comment by GuidoBartoli** [comment]
The one that I wrote: `pip list`. You must execute it after activating your newly created virtual environment with `workon sq` as explained [here](https://github.com/GuidoBartoli/sherloq#installation). It display all the currently installed packages in order to check if PySide6 is present, since that is the error you receive.

**Comment by DonaldLaborde** [comment]
Thanjks a lot for helping me. I did it as you said and the result is :+1: 

```
(sq) osint@osint:~$ pip list
Package    Version
---------- -------
pip        22.3.1
setuptools 65.6.3
wheel      0.38.4

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
(sq) osint@osint:~$ 
```
I hope it is what you expected, have a nice day

**Comment by GuidoBartoli** [comment]
Judging from the output, you successfully created the `sq` virtual environment, but you did not install the required packages to run the program. This is explained in the [second step](https://github.com/GuidoBartoli/sherloq#22-launch-program) of the installation, you just need to pass the `requirements.txt` file to `pip` (before that, I suggest you to update it as well with `pip install --upgrade pip`).

Let me know if it works then.

**Comment by DonaldLaborde** [comment]
1 - I changed de current directory : cd '/home/osint/Downloads/Programs/sherloq/gui’

2 - I update pip : pip install --upgrade pip

3 - I executed : pip install -r requirements.txt


Then to launch the program
4 - python sherloq.py

I got the same issue :

ERROR: Could not find a version that satisfies the requirement pyside6==6.3.2 (from versions: none)
ERROR: No matching distribution found for pyside6==6.3.2
(sq) ***@***.***:~/Downloads/Programs/sherloq/gui$ python sherloq.py
Traceback (most recent call last):
  File "/home/osint/Downloads/Programs/sherloq/gui/sherloq.py", line 4, in <module>
    from PySide6.QtCore import Qt, QSettings
ModuleNotFoundError: No module named 'PySide6'
(sq) ***@***.***:~/Downloads/Programs/sherloq/gui$ pip install --upgrade pip
Requirement already satisfied: pip in /home/osint/.virtualenvs/sq/lib/python3.10/site-packages (23.1.2)
(sq) ***@***.***:~/Downloads/Programs/sherloq/gui$ 

So sorry to take your time but I think there is something I don't understand?

Bien cordialement,
___________________________________________________________
Jean-Michel Metzger
148, avenue Rose de Mai    iPhone :    +33 (0)6 18 03 65 95
83600 Fréjus (PACA)	   mailto :   ***@***.***
France	                   Internet :           judogokyo.com <https://www.judogokyo.com/>
___________________________________________________________

**Comment by DonaldLaborde** [comment]
If you could help, I think I did everything correctly but it seems a version of pyside6 is not the right one ?

ERROR: Could not find a version that satisfies the requirement pyside6==6.3.2 (from versions: none)
ERROR: No matching distribution found for pyside6==6.3.2
(sq) osint@osint:~/Downloads/Programs/sherloq/gui$ python sherloq.py
Traceback (most recent call last):
  File "/home/osint/Downloads/Programs/sherloq/gui/sherloq.py", line 4, in <module>
    from PySide6.QtCore import Qt, QSettings
ModuleNotFoundError: No module named 'PySide6'
(sq) osint@osint:~/Downloads/Programs/sherloq/gui$ 

Thanks again if you could help

**Comment by GuidoBartoli** [comment]
What distribution are you using? Can you please show me the output of `neofetch` command from terminal?

**Comment by DonaldLaborde** [comment]
neofetch was not installed, so I installed just now and it gives now as follow :

￼

But the result doesn’t change to launch the program

Bien cordialement,
___________________________________________________________
Jean-Michel Metzger
148, avenue Rose de Mai    iPhone :    +33 (0)6 18 03 65 95
83600 Fréjus (PACA)	   mailto :   ***@***.***
France	                   Internet :           judogokyo.com <https://www.judogokyo.com/>
___________________________________________________________

**Comment by DonaldLaborde** [comment]
Oh wait, the image is not sent 👍 

 osint@osint 
        `:+ssssssssssssssssss+:`           ----------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 22.04.2 LTS aarch64 
    .ossssssssssssssssssdMMMNysssso.       Host: Apple Virtualization Generic Platform 1 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.19.0-45-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 11 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 1762 (dpkg), 15 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.1.16 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1200 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: GNOME 42.5 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Adwaita 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Yaru [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Yaru [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: gnome-terminal 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: (4) 
    .ossssssssssssssssssdMMMNysssso.       GPU: 00:07.0 Red Hat, Inc. Virtio GPU 
      -+sssssssssssssssssyyyssss+-         Memory: 1076MiB / 7930MiB 
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.
