### ISSUE TITLE
ImportError: cannot import name 'convert_dict_qtables' from 'PIL.JpegImagePlugin'

### ISSUE THREAD

**Issue by bdrajer** [GuidoBartoli/sherloq#71]
I get this error starting Sherloq on Windows, running Python 3.10.11 64-bit... Tried to find similar errors on the net, with no success. 

C:\sherlok\gui>workon sq
(sq) C:\sherlok\gui>py sherloq.py
WARNING:tensorflow:From C:\Users\xxxxxx\Envs\sq\lib\site-packages\tensorflow\python\compat\v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "C:\sherlok\gui\sherloq.py", line 34, in <module>
    from splicing import SplicingWidget
  File "C:\sherlok\gui\splicing.py", line 13, in <module>
    from noiseprint.noiseprint_blind import genMappUint8
  File "C:\sherlok\gui\noiseprint\noiseprint_blind.py", line 18, in <module>
    from .utility.utilityRead import resizeMapWithPadding
  File "C:\sherlok\gui\noiseprint\utility\utilityRead.py", line 13, in <module>
    from PIL.JpegImagePlugin import convert_dict_qtables
ImportError: cannot import name 'convert_dict_qtables' from 'PIL.JpegImagePlugin' (C:\Users\xxxxxx\Envs\sq\lib\site-packages\PIL\JpegImagePlugin.py)

Any help will be greatly appreciated.

**Comment by GuidoBartoli** [comment]
Seems something related to JPEG management of PIL library under Windows. Can you please report me the output of `pip list` to see the package versions inside your virtual environment?

**Comment by bdrajer** [comment]
Here it is:

(sq) C:\Users\xxxxx>pip list
Package                        Version
------------------------------ --------
absl-py                        1.4.0
astor                          0.8.1
astunparse                     1.6.3
cachetools                     5.3.1
certifi                        2023.5.7
charset-normalizer             3.1.0
concurrent-iterator            0.2.6
contourpy                      1.1.0
cycler                         0.11.0
decorator                      5.1.1
flatbuffers                    23.5.26
fonttools                      4.40.0
gast                           0.4.0
google-auth                    2.21.0
google-auth-oauthlib           0.4.6
google-pasta                   0.2.0
grpcio                         1.56.0
h5py                           3.9.0
idna                           3.4
imageio                        2.31.1
joblib                         1.3.1
keras                          2.11.0
Keras-Applications             1.0.8
kiwisolver                     1.4.4
libclang                       16.0.0
lxml                           4.9.1
Markdown                       3.4.3
MarkupSafe                     2.1.3
matplotlib                     3.6.0
networkx                       3.1
numpy                          1.25.0
oauthlib                       3.2.2
opencv-contrib-python-headless 4.6.0.66
opt-einsum                     3.3.0
packaging                      23.1
pandas                         1.5.0
Pillow                         10.0.0
pip                            23.1.2
protobuf                       3.19.6
pyasn1                         0.5.0
pyasn1-modules                 0.3.0
pyparsing                      3.1.0
PySide6                        6.3.2
PySide6-Addons                 6.3.2
PySide6-Essentials             6.3.2
python-dateutil                2.8.2
python-magic                   0.4.27
python-magic-bin               0.4.14
pytz                           2023.3
PyWavelets                     1.4.1
rawpy                          0.17.2
requests                       2.31.0
requests-oauthlib              1.3.1
rsa                            4.9
scikit-image                   0.19.3
scikit-learn                   1.1.2
scipy                          1.11.1
setuptools                     67.8.0
sewar                          0.4.5
shiboken6                      6.3.2
six                            1.16.0
tensorboard                    2.11.2
tensorboard-data-server        0.6.1
tensorboard-plugin-wit         1.8.1
tensorflow                     2.11.1
tensorflow-estimator           2.11.0
tensorflow-intel               2.11.1
tensorflow-io-gcs-filesystem   0.31.0
termcolor                      2.3.0
threadpoolctl                  3.1.0
tifffile                       2023.7.4
typing_extensions              4.7.1
urllib3                        1.26.16
Werkzeug                       2.3.6
wheel                          0.40.0
wrapt                          1.15.0
xgboost                        1.6.2

Thanks!

**Comment by slonyarakmw** [comment]
Same Problem!

**Comment by GuidoBartoli** [comment]
Seems related to #72, I'm waiting for some updates from users on that.

I am realizing more and more that the inclusion of `tensorflow` package to run the [Noiseprint](https://grip-unina.github.io/noiseprint/) algorithm is bringing a lot of problems running with the various operating systems, and I am seriously considering eliminating it in favor of the newer [TruFor](https://github.com/grip-unina/TruFor) which is instead based on PyTorch instead.

**Comment by gmhuestis** [comment]
I think Pillow removed support for convert_dict_qtables in version 10. Try an older version:
```
pip uninstall pillow
pip install pillow==9.5
```
That worked for me

**Comment by GuidoBartoli** [comment]
Fixed in 2c7a07c, many thanks!
