### ISSUE TITLE
ImportError: cannot import name 'convert_dict_qtables' from 'PIL.JpegImagePlugin' (/home/wt/.virtualenvs/sq/lib/python3.10/site-packages/PIL/JpegImagePlugin.py)

### ISSUE THREAD

**Issue by willtanoe** [GuidoBartoli/sherloq#72]
I'm using ubuntu 22.04
this is the output i got

> (sq) wt@wt-sherloq:~/sherloq/gui$ python sherloq.py
> WARNING:tensorflow:From /home/wt/.virtualenvs/sq/lib/python3.10/site-packages/tensorflow/python/compat/v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
> Instructions for updating:
> non-resource variables are not supported in the long term
> Traceback (most recent call last):
>   File "/home/wt/sherloq/gui/sherloq.py", line 34, in <module>
>     from splicing import SplicingWidget
>   File "/home/wt/sherloq/gui/splicing.py", line 13, in <module>
>     from noiseprint.noiseprint_blind import genMappUint8
>   File "/home/wt/sherloq/gui/noiseprint/noiseprint_blind.py", line 18, in <module>
>     from .utility.utilityRead import resizeMapWithPadding
>   File "/home/wt/sherloq/gui/noiseprint/utility/utilityRead.py", line 13, in <module>
>     from PIL.JpegImagePlugin import convert_dict_qtables
> ImportError: cannot import name 'convert_dict_qtables' from 'PIL.JpegImagePlugin' (/home/wt/.virtualenvs/sq/lib/python3.10/site-packages/PIL/JpegImagePlugin.py)
> (sq) wt@wt-sherloq:~/sherloq/gui$

For the pip list output

> (sq) wt@wt-sherloq:~/sherloq/gui$ pip list
> Package                        Version
> ------------------------------ ---------
> absl-py                        1.4.0
> astor                          0.8.1
> astunparse                     1.6.3
> cachetools                     5.3.1
> certifi                        2023.7.22
> charset-normalizer             3.2.0
> concurrent-iterator            0.2.6
> contourpy                      1.1.0
> cycler                         0.11.0
> decorator                      5.1.1
> flatbuffers                    23.5.26
> fonttools                      4.41.1
> gast                           0.4.0
> google-auth                    2.22.0
> google-auth-oauthlib           0.4.6
> google-pasta                   0.2.0
> grpcio                         1.56.2
> h5py                           3.9.0
> idna                           3.4
> imageio                        2.31.1
> joblib                         1.3.1
> keras                          2.11.0
> Keras-Applications             1.0.8
> kiwisolver                     1.4.4
> libclang                       16.0.6
> lxml                           4.9.1
> Markdown                       3.4.3
> MarkupSafe                     2.1.3
> matplotlib                     3.6.0
> networkx                       3.1
> numpy                          1.25.1
> oauthlib                       3.2.2
> opencv-contrib-python-headless 4.6.0.66
> opt-einsum                     3.3.0
> packaging                      23.1
> pandas                         1.5.0
> Pillow                         10.0.0
> pip                            23.2.1
> protobuf                       3.19.6
> pyasn1                         0.5.0
> pyasn1-modules                 0.3.0
> pyparsing                      3.1.0
> PySide6                        6.3.2
> PySide6-Addons                 6.3.2
> PySide6-Essentials             6.3.2
> python-dateutil                2.8.2
> python-magic                   0.4.27
> pytz                           2023.3
> PyWavelets                     1.4.1
> rawpy                          0.17.2
> requests                       2.31.0
> requests-oauthlib              1.3.1
> rsa                            4.9
> scikit-image                   0.19.3
> scikit-learn                   1.1.2
> scipy                          1.11.1
> setuptools                     68.0.0
> sewar                          0.4.5
> shiboken6                      6.3.2
> six                            1.16.0
> tensorboard                    2.11.2
> tensorboard-data-server        0.6.1
> tensorboard-plugin-wit         1.8.1
> tensorflow                     2.11.1
> tensorflow-estimator           2.11.0
> tensorflow-io-gcs-filesystem   0.32.0
> termcolor                      2.3.0
> threadpoolctl                  3.2.0
> tifffile                       2023.7.18
> typing_extensions              4.7.1
> urllib3                        1.26.16
> Werkzeug                       2.3.6
> wheel                          0.40.0
> wrapt                          1.15.0
> xgboost                        1.6.2
> (sq) wt@wt-sherloq:~/sherloq/gui$

Any help will be greatly appreciated.
Thanks!

**Comment by slonyarakmw** [comment]
Same problem :(

**Comment by Alex-Faulkner** [comment]
I have the same problem, according to this: https://pillow.readthedocs.io/en/stable/releasenotes/8.3.0.html the convert_dict_qtables is now done automatically and the method has been depreciated.
I managed to get the software running by deleting line 13 from /home/wt/sherloq/gui/noiseprint/utility/utilityRead.py and editing line 83 to remove the convert_dict_qtables call.

**Comment by pradeepkc11** [comment]
downgrade the Pillow version from 10.0.0 to 8.4.0 by
using 
pip uninstall pillow
pip install pillow==8.4.0

**Comment by GuidoBartoli** [comment]
Thanks @Alex-Faulkner for looking into this. Does the Tampering Detection module still work without that line of code?

**Comment by pradeepkc11** [comment]
Sorry,
I just come across the tool recently while trying to run sherlog.py I faced
the convert_dict_qtables error I have not gone across whole
features, if you can let me know of all the python scripts which script you
are having problem with let me know with
further details so that i can work on it and also it was fun while
debugging this problem,
Thanks and regards,
Pradeep k c

**Comment by slonyarakmw** [comment]
I don't now how, but it's all starts working :). I did many upgrades, deleting, installing, and now - it working. Thanks to @GuidoBartoli fo this programm! Very nice soft!

**Comment by Huitzil0p0chtli** [comment]
For anyone struggling, do the following....

delete line 13 from sherloq/gui/noiseprint/utility/utilityRead.py and editing line 83 to remove the convert_dict_qtables call. Will fix error on sherloq gui.


on line 83 delete the following phrase:

(convert_dict_qtables(Image.open(stream).quantization)[tnum]).reshape((8, 8))

new line should look like the following

h = np.asarray

**Comment by GuidoBartoli** [comment]
> For anyone struggling, do the following....
> 
> delete line 13 from sherloq/gui/noiseprint/utility/utilityRead.py and editing line 83 to remove the convert_dict_qtables call. Will fix error on sherloq gui.
> 
> on line 83 delete the following phrase:
> 
> (convert_dict_qtables(Image.open(stream).quantization)[tnum]).reshape((8, 8))
> 
> new line should look like the following
> 
> h = np.asarray

Thanks @Huitzil0p0chtli 👍🏻
