### ISSUE TITLE
Traceback Errors

### ISSUE THREAD

**Issue by dindal101** [GuidoBartoli/sherloq#79]
getting these errors, could you help?

```python3 sherloq.py 
WARNING:tensorflow:From /home/seeker/.virtualenvs/sq/lib/python3.10/site-packages/tensorflow/python/compat/v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "/home/seeker/Documents/Programs/sherloq/sherloq/gui/sherloq.py", line 34, in <module>
    from splicing import SplicingWidget
  File "/home/seeker/Documents/Programs/sherloq/sherloq/gui/splicing.py", line 13, in <module>
    from noiseprint.noiseprint_blind import genMappUint8
  File "/home/seeker/Documents/Programs/sherloq/sherloq/gui/noiseprint/noiseprint_blind.py", line 18, in <module>
    from .utility.utilityRead import resizeMapWithPadding
  File "/home/seeker/Documents/Programs/sherloq/sherloq/gui/noiseprint/utility/utilityRead.py", line 13, in <module>
    from PIL.JpegImagePlugin import convert_dict_qtables
ImportError: cannot import name 'convert_dict_qtables' from 'PIL.JpegImagePlugin' (/home/seeker/.virtualenvs/sq/lib/python3.10/site-packages/PIL/JpegImagePlugin.py)```

**Comment by revmischa** [comment]
Same here, on Ubuntu

**Comment by sans-c** [comment]
Just ran into this, too. If you need any more info, let me know.

**Comment by andre-santos1** [comment]
Not working for Debian. I will paste the error here.


pip install -U "Pillow < 8.3"
Collecting Pillow<8.3
  Downloading Pillow-8.2.0.tar.gz (47.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.9/47.9 MB 2.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: Pillow
  Building wheel for Pillow (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [185 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-311
      creating build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/SunImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/DdsImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageCms.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PaletteFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ContainerIO.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ExifTags.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/JpegPresets.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/BdfFontFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/_util.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/MicImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/BlpImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/FontFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageEnhance.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageDraw2.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/FliImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageGrab.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageFont.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageMode.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageColor.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageStat.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/__main__.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageTk.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageDraw.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/TiffTags.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PcfFontFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageFilter.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GifImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/WalImageFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImagePalette.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/_binary.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImagePath.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/_tkinter_finder.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageWin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageShow.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/__init__.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PyAccess.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageQt.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PSDraw.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PngImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PdfParser.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GdImageFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/FtexImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/features.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/CurImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageTransform.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageMorph.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/TarIO.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageChops.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/MspImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageMath.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GimpGradientFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/Image.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageSequence.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/_version.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageOps.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      running egg_info
      writing src/Pillow.egg-info/PKG-INFO
      writing dependency_links to src/Pillow.egg-info/dependency_links.txt
      writing top-level names to src/Pillow.egg-info/top_level.txt
      reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c'
      warning: no files found matching '*.h'
      warning: no files found matching '*.sh'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.clang-format'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching '.editorconfig'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files matching '.git*' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      no previously-included directories found matching '.ci'
      adding license file 'LICENSE'
      writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
      running build_ext
      
      
      The headers or library files could not be found for jpeg,
      a required dependency when compiling Pillow from source.
      
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
      
      Traceback (most recent call last):
        File "/tmp/pip-install-31iqiee3/pillow_e7ed6cf59a8d4260af035492af2a37e6/setup.py", line 976, in <module>
          setup(
        File "/home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/tmp/pip-install-31iqiee3/pillow_e7ed6cf59a8d4260af035492af2a37e6/setup.py", line 788, in build_extensions
          raise RequiredDependencyException(f)
      RequiredDependencyException: jpeg
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-31iqiee3/pillow_e7ed6cf59a8d4260af035492af2a37e6/setup.py", line 1033, in <module>
          raise RequiredDependencyException(msg)
      RequiredDependencyException:
      
      The headers or library files could not be found for jpeg,
      a required dependency when compiling Pillow from source.
      
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Pillow
  Running setup.py clean for Pillow
Failed to build Pillow
Installing collected packages: Pillow
  Attempting uninstall: Pillow
    Found existing installation: pillow 10.2.0
    Uninstalling pillow-10.2.0:
      Successfully uninstalled pillow-10.2.0
  Running setup.py install for Pillow ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for Pillow did not run successfully.
  │ exit code: 1
  ╰─> [190 lines of output]
      running install
      /home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-311
      creating build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/SunImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/DdsImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageCms.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PaletteFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ContainerIO.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ExifTags.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/JpegPresets.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/BdfFontFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/_util.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/MicImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/BlpImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/FontFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageEnhance.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageDraw2.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/FliImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageGrab.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageFont.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageMode.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageColor.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageStat.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/__main__.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageTk.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageDraw.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/TiffTags.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PcfFontFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageFilter.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GifImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/WalImageFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImagePalette.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/_binary.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImagePath.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/_tkinter_finder.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageWin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageShow.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/__init__.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PyAccess.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageQt.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PSDraw.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PngImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PdfParser.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GdImageFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/FtexImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/features.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/CurImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageTransform.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageMorph.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/TarIO.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageChops.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/MspImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageMath.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GimpGradientFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/Image.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageSequence.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/_version.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageOps.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      running egg_info
      writing src/Pillow.egg-info/PKG-INFO
      writing dependency_links to src/Pillow.egg-info/dependency_links.txt
      writing top-level names to src/Pillow.egg-info/top_level.txt
      reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c'
      warning: no files found matching '*.h'
      warning: no files found matching '*.sh'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.clang-format'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching '.editorconfig'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files matching '.git*' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      no previously-included directories found matching '.ci'
      adding license file 'LICENSE'
      writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
      running build_ext
      
      
      The headers or library files could not be found for jpeg,
      a required dependency when compiling Pillow from source.
      
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
      
      Traceback (most recent call last):
        File "/tmp/pip-install-31iqiee3/pillow_e7ed6cf59a8d4260af035492af2a37e6/setup.py", line 976, in <module>
          setup(
        File "/home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/setuptools/_distutils/command/install.py", line 698, in run
          self.run_command('build')
        File "/home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/tmp/pip-install-31iqiee3/pillow_e7ed6cf59a8d4260af035492af2a37e6/setup.py", line 788, in build_extensions
          raise RequiredDependencyException(f)
      RequiredDependencyException: jpeg
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-31iqiee3/pillow_e7ed6cf59a8d4260af035492af2a37e6/setup.py", line 1033, in <module>
          raise RequiredDependencyException(msg)
      RequiredDependencyException:
      
      The headers or library files could not be found for jpeg,
      a required dependency when compiling Pillow from source.
      
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of pillow
  Moving to /home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/PIL/
   from /home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/~IL
  Moving to /home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/pillow-10.2.0.dist-info/
   from /home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/~illow-10.2.0.dist-info
  Moving to /home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/pillow.libs/
   from /home/osint/Programs/sherloqEnvironment/sherloqEnvironment/lib/python3.11/site-packages/~illow.libs
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> Pillow

**Comment by cheeeeee** [comment]
`pip install Pillow==9.2` @dindal101

**Comment by GuidoBartoli** [comment]
Thanks @cheeeeee, I will update the requirements accordingly.
