### ISSUE TITLE
Using float32 in PCA calculation can cause erroneous means. Recommend using float64

### ISSUE THREAD

**Issue by atadams** [GuidoBartoli/sherloq#91]
@GuidoBartoli, thanks for addressing this issue. This does resolve the clipping issues. But, after further investigation, I believe there is still one problem. The issue with the same PCA means is related to auto_brightness, but is actually due to the image being cast as `np.float32` in line 40 of pca.py.

```x = np.reshape(image, (rows * cols, chans)).astype(np.float32)```

When the mean is calculated, it limits the sum of the pixels to 2^32. That limited sum is divided by the number of pixels to get the erroneous mean. This isn't limited to raw files. It has to do with the size and values of the pixels, i.e., the sums of larger and brighter (higher pixel values) images are more likely to reach the 2^32 limit.

You can test this by creating a large, solid light-color image, noting the RGB values (I used 180, 220, 241)

![image](https://github.com/GuidoBartoli/sherloq/assets/392510/6c1da1d7-c0dd-4d70-80fc-9726feb768f5)

When you run the PCA tool on the image, the means should equal the RGB values of our solid, but they don't and are equal. To further illustrate the issue, if you divide 2^32 by the number of pixels, you will get the displayed erroneous mean.

```(2^32)/(4500*6000) = 159.07286```

Changing the `np.float32` to `np.float64` will resolve the same PCA means issue as shown by the displayed means matching the image's RGB values.

![image](https://github.com/GuidoBartoli/sherloq/assets/392510/09f053bc-d75a-477e-950e-838316e56c4b)

I believe we mistook this for a raw file issue because raw files are typically large and because rawpy brightens and white balances the image when postprocessing is done. This increases the pixel values, making it more likely that the 2^32 limit will be reached when summed for the mean calculation.

_Originally posted by @atadams in https://github.com/GuidoBartoli/sherloq/issues/86#issuecomment-2180406316_

**Comment by GuidoBartoli** [comment]
Fixed in d6a3b98e7fb88dc41bd3caa70d8160b20d330d48.
