### ISSUE TITLE
Eigenvector values are missing, and EigenValue variance is still huge

### ISSUE THREAD

**Issue by Ray9T** [GuidoBartoli/sherloq#92]
@GuidoBartoli 
PCA,>EigenValues, EigenVector is broken, and the huge variance mentioned is still present.

For eigenvalue issue, please see below. Besides the missing values, as expected np.float64 is only adding to latency, where np.float32 was more than adequate for this operation. 

> [d6a3b98](https://github.com/GuidoBartoli/sherloq/commit/d6a3b98e7fb88dc41bd3caa70d8160b20d330d48), many thanks!

Images in the test
Test image 1: https://www.imaging-resource.com/PRODS/sony-a99-ii/A99M2hSLI000050NR0.ARW.HTM
Test Image 2 : https://www.imaging-resource.com/PRODS/sony-a99-ii/A99M2hSLI000050NR2D.ARW.HTM

![image](https://github.com/GuidoBartoli/sherloq/assets/165091653/d7ed861a-0fd5-48f4-83b9-18738b85dc23)

![image](https://github.com/GuidoBartoli/sherloq/assets/165091653/11513b8a-3ca2-4b44-804f-532973932545)

**Comment by Ray9T** [comment]
@GuidoBartoli to add, appreciate if we can have a test branch and not have to merge changes directly to main branch, until fully tested. 
From my various tests, it appears like version 0.87c from 1-2 weeks ago is still the most stable and usable version for detecting image fabrications.

**Comment by GuidoBartoli** [comment]
Values are not missing, simply they have too much decimals to be displayed inside the table, you just need to resize the columns.

However, I applied PCA to the [first image](https://www.imaging-resource.com/PRODS/sony-a99-ii/A99M2hSLI000050NR0.ARW.HTM) you provided and this is the result:
![1](https://github.com/GuidoBartoli/sherloq/assets/16103676/445f63b0-451f-47f4-adc5-285cc89c2527)
While this is the PCA of the [second one](https://www.imaging-resource.com/PRODS/sony-a99-ii/A99M2hSLI000050NR2D.ARW.HTM):
![2](https://github.com/GuidoBartoli/sherloq/assets/16103676/62f403b0-1998-4388-9636-15939cd0f962)

You can clearly see that the values differ very slightly, which is in line with the fact that the images are very similar.

Please update to 0.89d version I just committed in c9a73ca5713f160cc12a20fd1c94e59e0d1fb512.

**Comment by Ray9T** [comment]
@GuidoBartoli Thanks for looking into it. 
For the first image, we are both getting identical results, but 2nd image shows a very different value (nearly 50% less)
I performed a clen setup for 0.89d. 

First image
![image](https://github.com/GuidoBartoli/sherloq/assets/165091653/0e34bcef-61b5-473c-a672-3bf9869e982b)

Second image
![image](https://github.com/GuidoBartoli/sherloq/assets/165091653/55378440-3336-41a2-acee-f22a9ce25848)
