### ISSUE TITLE
I built a exe version of this tool which can run it without python environment

### ISSUE THREAD

**Issue by sdy623** [GuidoBartoli/sherloq#98]
<img width="779" alt="image" src="https://github.com/GuidoBartoli/sherloq/assets/70808322/a232aaa8-2dab-467e-a027-a407d977344e">

**Comment by GuidoBartoli** [comment]
Please provide more info and context on this, even better a pull request, otherwise I can close this issue.

**Comment by sdy623** [comment]
Ok I will create a commit of the nuitka build scripts and innosetup install script , but I don’t know how to use CI workflow to make this.
