### ISSUE TITLE
no_auto_scale=True can cause significant clipping and data loss

### ISSUE THREAD

**Issue by atadams** [GuidoBartoli/sherloq#99]
In v0.89f, adding the `no_auto_scale=True` parameter to the `raw.postprocess` in the `load_image` function (`utility.py`) can cause significant clipping and data loss when opening a RAW file. This is illustrated by view the histogram of this [real-world, naturally taken gallery image](https://www.imaging-resource.com/PRODS/canon-7d-mark-ii/YAK4A0834.CR2.HTM) from Imaging Resource.

**Red and blue histogram with v0.89f no_auto_scale=True parameter**
<img width="1470" alt="issue-noscaling" src="https://github.com/GuidoBartoli/sherloq/assets/392510/c7d36f62-f9ae-4058-8db2-9fc038006d6e">

You can see a large percentage of red and blue pixels have 0 intensity and the image has a strong green tint. I believe the clipping is happening because the black levels are still being subtracted. With other images, the R, G, or B channels can be entirely 0 values.

Alex Tutubalin, the developer of Libraw, has stated, “no_auto_ scale is very special use parameter.”

![libraw-01](https://github.com/GuidoBartoli/sherloq/assets/392510/38b23684-9bc2-4ecf-b242-d1e50525d950)

You can see the results of removing the `no_auto_scale=True` parameter in the histograms below.

**Red and blue histogram with no_auto_scale=True parameter _removed_**
<img width="900" alt="issue-scaling" src="https://github.com/GuidoBartoli/sherloq/assets/392510/cb98bd02-81e5-4b01-82f7-86b678514f5c">

The image’s color is more balanced and you can see the number of pixels with 0 intensity is significantly reduced. 

### Recommendation
I recommend removing the `no_auto_scale=True` parameter from the `load_image function` in `utility.py`.

Thank you.

**Comment by Ray9T** [comment]
@atadams I think your use of "Data loss" is very misleading. The data is there, just no scaling.
Meaning you're seeing the data as the sensor sees the photons and intensity ratios with `no_auto_scale=True`
If you adjust the brightness and other params, the image starts to appear. 

This is expected behavior of reading unprocessed RAW data. Please focus on your objective and not specific settings, as your fundamentals of RAW and image processing is flawed, and it's best if you ask what you need instead of invalid suggestions. 

If you need your specific image discussed, im happy to break it down for you based on latest Sherloq app behavior, which is doing it's job as a forensic app and not an image viewer. 

Again, your image Data is there and not lost my friend.

**Comment by JohnConnor01** [comment]
@GuidoBartoli I am happy to provide corroborated results from another application. When it comes to the Red Channel and the Camera Sensors with the 19 photos referenced in the previous issue. Showing this is an issue with the photos. And not the application. We have overwhelming evidence at this point. 

If you would prefer us share this information publicly. Please let us know we can begin putting everything together. I would just ask for 48-72 hours from the time of notification as it will take some time to put everything together.

**Comment by TJPofTexas** [comment]
JohnConnor01, are you also BobbyoO_ on Twitter / X?

"We have overwhelming evidence at this point."

I know you may be overwhelmed because your primary experience is trading memecoins, but Canon Digital Photo Professional 4.0 is the only manufacturer created utility for processing CR2 raw files and the results when processing the RAW with the Canon software, (or with just about any other raw software, rawdigger, darktable, etc) it's plain to see that the processing method in the current version of Sherloq is not properly debayering and scaling the non-green channels.

![image](https://github.com/GuidoBartoli/sherloq/assets/173004318/506ac841-af06-41d0-869d-0bce2965b2fd)
![image](https://github.com/GuidoBartoli/sherloq/assets/173004318/5cc11382-32e4-418c-b2a8-15ddb59e5133)

**Comment by Ray9T** [comment]
> @GuidoBartoli I am happy to provide corroborated results from another application. When it comes to the Red Channel and the Camera Sensors with the 19 photos referenced in the previous issue. Showing this is an issue with the photos. And not the application. We have overwhelming evidence at this point.
> 
> If you would prefer us share this information publicly. Please let us know we can begin putting everything together. I would just ask for 48-72 hours from the time of notification as it will take some time to put everything together.

Indeed, we need to now start understanding how some images are unique or anomolous and not continue to change the app until the problem goes away. 
In the case of Tony he does not even understand the basics of histogram and how it applies to images.

The pixels are all there, the data is there, but without scaling the raw data is showing linear ratios, which is what the camera sensor registered. 
I'd love to have this function in any forensic app. The issue is clearly with images and maybe it's better to review the images and not blame the software.

**Comment by Ray9T** [comment]
> JohnConnor01, are you also BobbyoO_ on Twitter / X?
> 
> "We have overwhelming evidence at this point."
> 
> I know you may be overwhelmed because your primary experience is trading memecoins, but Canon Digital Photo Professional 4.0 is the only manufacturer created utility for processing CR2 raw files and the results when processing the RAW with the Canon software, (or with just about any other raw software, rawdigger, darktable, etc) it's plain to see that the processing method in the current version of Sherloq is not properly debayering and scaling the non-green channels.
> 
> ![image](https://private-user-images.githubusercontent.com/173004318/344486385-506ac841-af06-41d0-869d-0bce2965b2fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NzIwMTksIm5iZiI6MTcxOTc3MTcxOSwicGF0aCI6Ii8xNzMwMDQzMTgvMzQ0NDg2Mzg1LTUwNmFjODQxLWFmMDYtNDFkMC04NjlkLTBiY2UyOTY1YjJmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQxODIxNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDEzZGVhMWZkN2VlMTM1YzNmYWFmZDRlOWYyMjE2YTg0NTNmOWY5NDcwY2RmZDkwMjAyNTFjOWZlZjI4MmFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iG1n2FlkXo2CzScdAqpVEwcCuZyf9pac93Shhm-wikk) ![image](https://private-user-images.githubusercontent.com/173004318/344486539-5cc11382-32e4-418c-b2a8-15ddb59e5133.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NzIwMTksIm5iZiI6MTcxOTc3MTcxOSwicGF0aCI6Ii8xNzMwMDQzMTgvMzQ0NDg2NTM5LTVjYzExMzgyLTMyZTQtNDE4Yy1iMmE4LTE1ZGRiNTllNTEzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQxODIxNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzU5ZmQ0MmJkMzRkNTg5YmJlNzYzNGFjMTc3MTVhNDI3NmRkYmU4MTkxZTE2NzA2N2FkMWY0YmUyMDBlNzkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.imP-iFq9YfSewokQT2H65XplGnudPEj8x1VHhmE1zH4)

This image is not "close to unprocessed" as it's already applying some scaling to make the image viewable. 
![image](https://github.com/GuidoBartoli/sherloq/assets/165091653/cc853cdd-c0ea-4ad8-b831-30e1a11145d2)


Again, this is poor fundamentals of image processing from some people and dare I say, misleading the forensics app to turn it into an image viewer.

**Comment by TJPofTexas** [comment]
To you, poor fundamentals is opening a raw file in the factory, standard RAW file ingesting software.

Sounds like you're trying to perpetrate some kind of fraud relative to these images Jonas took.

![image](https://github.com/GuidoBartoli/sherloq/assets/173004318/93610f52-160e-4449-9904-09b5d15b3504)

**Comment by TJPofTexas** [comment]
So glad that Ray9T has made this graphic to show they have no idea how color scale settings can result in leaving data out of range, and thus omitted, on conversion from CR2 RAW to other image formats.

![image](https://github.com/GuidoBartoli/sherloq/assets/173004318/62f73847-23bf-4ad0-b0ab-c230d028b5e3)

**Comment by atadams** [comment]
> Link to 19 photos associated with Tony and many of his colleagues. The results of these 19 photos on the current version of Sherloq CAN be corroborated on a different application. Along with significantly more information with camera sensors on all 19 photos.

Aren’t you claiming the images have no red channel? 

It is true that when those images are opened in the current version of Sherloq, the red channels are only zero values. This is explained by my opening comment in this issue. That does not mean the red channel doesn’t exist, only that that is being “zeroed out” when the black levels are subtracted. 

I welcome Guido to look and any or all of those images as an illustration of this issue I described above.

**Comment by atadams** [comment]
> In the case of Tony, he does not understand the basics of histogram and how it applies to images. 

This is rude and uncalled for.

**Comment by JohnConnor01** [comment]
> > Link to 19 photos associated with Tony and many of his colleagues. The results of these 19 photos on the current version of Sherloq CAN be corroborated on a different application. Along with significantly more information with camera sensors on all 19 photos.
> 
> Aren’t you claiming the images have no red channel?
> 
> It is true that when those images are opened in the current version of Sherloq, the red channels are only zero values. This is explained by my opening comment in this issue. That does not mean the red channel doesn’t exist, only that the red channel is being “zeroed out” when the black levels are subtracted.
> 
> I welcome Guido to look and any or all of those images as an illustration of this issue I described above.


Hello

Please re-read my comment. The results of the current version of Sherloq (Gudio’s recommendation/compromise) with the 19 photos linked. Can be corroborated using another application. Ontop of that - significantly more information can be shown on the camera sensors on all 19 photos. Showing how this is an issue with the 19 photos - and not the application. 

I am simply asking for notice of how that information would like to be released. As it would provide supporting evidence that this version of Sherloq is not reading those 19 photos in error. 

There are distinct differences when analyzing these specific 19 RAW photos. And other RAW photos from Imagine Resource. And we are happy to illustrate that. And/or provide any/all additional supporting evidence. 

All RGB intensity values have been pushed to the left with post processing turned down to a minimum. That should have been expected. 
And turning auto scale back on (or using rawpy default) and the RGB intensity values increasing - should also be expected. 

The compromise was intended to avoid bias results. As stated on the previous issue. This is a sample size of 1 or 2 you are presenting while asking for wholesale changes again. 

But there are distinct differences with the 19 RAW photos linked. And many other RAW photos we have sampled. Those primarily show up in the Red Channel and/or Red mean vector PCA value. 

My position is the current version of Sherloq is not reading those 19 photos in error. And I am happy to show the corroborated results with another application. Plus overwhelmingly more evidence of/relating to the camera sensors on all 19 photos.

**Comment by atadams** [comment]
> My position is the current version of Sherloq is not reading those 19 photos in error. And I am happy to show the corroborated results with another application. Plus overwhelmingly more evidence of/relating to the camera sensors on all 19 photos.

This issue happens with _every_ RAW file opened — _including_ the 19 you reference.

**Comment by JohnConnor01** [comment]
@GuidoBartoli 

@atadams has raised another issue about clipping with RAW photos on the current version. The RGB intensity values are not getting scaled and showing linear proportions. Which is what you would expect reading the camera censor data. I would argue he is conflating two different things. This was supposed to be the version that minimized biased results. And we greatly appreciate you reaching that compromise. 

However if his recommendation is accepted and implemented. That will BRING BACK clipping with RAW photos. As highlighted below with two CR2 RAW photos from Imaging Resource. I will go back and find the link to the original photo so this can be replicated. **Tony's recommendation will bring back the very problem he said he was trying to solve.**
It appears there is big disconnect between what Tony says he wants, and the specific changes he is asking for.

**Example 1 of RAW Photo being clipped after no_auto_scale=true is removed**
![image](https://github.com/GuidoBartoli/sherloq/assets/173414082/53fdc722-e4ac-4d25-af5d-fb44fb5916e5)

**Example 2 of RAW Photo being clipped after no_auto_scale=true is removed**
![image](https://github.com/GuidoBartoli/sherloq/assets/173414082/5b6f1abe-4102-4c80-9b54-f1f127659994)

**Comment by BakersTutz** [comment]
@JohnConner01 looks like those images were already clipped _in camera_. Both of those images contain direct sunlight reflecting off the water. If the highlights are already clipped, Sherloq isn't going to unclip it.

**Comment by Ray9T** [comment]
> > Link to 19 photos associated with Tony and many of his colleagues. The results of these 19 photos on the current version of Sherloq CAN be corroborated on a different application. Along with significantly more information with camera sensors on all 19 photos.
> 
> Aren’t you claiming the images have no red channel?
> 
> It is true that when those images are opened in the current version of Sherloq, the red channels are only zero values. This is explained by my opening comment in this issue. That does not mean the red channel doesn’t exist, only that the red channel is being “zeroed out” when the black levels are subtracted.
> 
> I welcome Guido to look and any or all of those images as an illustration of this issue I described above.

**The right way to evaluate this is:**
-Stop making changes to the Sherloq. More so now considering we are as close to raw data as possible. 
-Understand why Tony's 19 images are so anomalous.

**Comment by atadams** [comment]
> That will BRING BACK clipping with RAW photos. 

The two examples you provided appear underexposed or overexposed. As Guido pointed out in a previous issue, there is nothing Sherloq should do about that.

**Comment by Ray9T** [comment]
> @JohnConnor01 looks like those images were already clipped _in camera_. Both of those images contain direct sunlight reflecting off the water. If the highlights are already clipped, Sherloq isn't going to unclip it.

Argument can be made that Tony's 19 images are already anomalous, and the sensor data is revealing the issues.

Anyway, the pretense that there is` data loss when in reality it's not scaling` shows poor fundamental understanding of RAW file concepts.

**Comment by atadams** [comment]
> It appears there is big disconnect between what Tony says he wants, and the specific changes he is asking for.

Also, could you please refrain from personal comments about me and just address the technical issues?

**Comment by Ray9T** [comment]
> > It appears there is big disconnect between what Tony says he wants, and the specific changes he is asking for.
> 
> Also, could you please refrain from personal comments about me and just address the technical issues?

You're misreading the statement. John said there's a disconnect between what's being asked, the rationale, and the specific settings you want to introduce to make the assumed problem go away.

Do you realize there is no data loss to begin with or is that still not clear to you?

**Comment by atadams** [comment]
> Understand why Tony's 19 images are so anomalous.

They aren't my images, but Guido is obviously free to use them in his investigation. The fact that, when opened in Sherloq, the red channels of those images are comprised entirely of zero values is an excellent example of the issue I'm describing.

**Comment by JohnConnor01** [comment]
**Test Photo 1**
https://www.imaging-resource.com/PRODS/canon-7d-mark-ii/Y071A1955-proto.CR2.HTM

**Test Photo 2**
https://www.imaging-resource.com/PRODS/canon-6d-mark-ii/Y_MG_1068.CR2.HTM

**Test Photo 1 on Current Version (No Clipping)** 
![image](https://github.com/GuidoBartoli/sherloq/assets/173414082/a748c810-cc4b-48c7-a84f-6bff2820a0d4)

**Test Photo 1 after no_auto_scale=true is REMOVED (Clipping)**
![image](https://github.com/GuidoBartoli/sherloq/assets/173414082/92689afb-5285-42db-9d48-f2d85a1030eb)

**Test Photo 2 on Current Version (No Clipping)**
![image](https://github.com/GuidoBartoli/sherloq/assets/173414082/f09ba021-cd7c-40dc-a4e2-044b7f826389)

**Test Photo 2 after no_auto_scale=true is REMOVED (Clipping)**
![image](https://github.com/GuidoBartoli/sherloq/assets/173414082/7b94045d-4ee7-4032-a76b-e1c6ebe84185)


If the issue is: Clipping with RAW Photos. It appears Tony's recommendation will only increase the frequency at which RAW Photos are clipped while using Sherloq. The compromise again was intended to avoid bias results.

**Comment by JohnConnor01** [comment]
> > Understand why Tony's 19 images are so anomalous.
> 
> They aren't my images, but Guido is obviously free to use them in his investigation. The fact that, when opened in Sherloq, the red channels of those images are comprised entirely of zero values is an excellent example of the issue I'm describing.


"the red channels of those images are comprised entirely of zero values is an excellent example of the issue I'm describing" 

Tony, have you checked other sources to see if they corroborate these results? Because we have. And other sources corroborate these very results.

**Comment by Ray9T** [comment]
> They aren't my images, but Guido is obviously free to use them in his investigation. The fact that, when opened in Sherloq, the red channels of those images are comprised entirely of zero values is an excellent example of the issue I'm describing.

Good, then respectfully, let's investigate and not rule images out as a problem. 
Blaming the software to cause data loss is getting old and shows lack of fundamental understanding of RAW file processing.

**Comment by atadams** [comment]
> Tony, have you checked other sources to see if they corroborate these results? Because we have. And other sources corroborate these very results.

Yes, I have checked other sources. The 19 images you refer to all have red channels in every imaging app I've tried. To claim they don't is not reasonable. 

If you have information that will help Guido make a decision, I suggest you provide it.

**Comment by atadams** [comment]
> Good, then respectfully, let's investigate and not rule images out as a problem.
> Blaming the software to cause data loss is getting old and shows lack of fundamental understanding of RAW file processing.

I'll ask again that you stop with the personal attacks.

**Comment by atadams** [comment]
> If the issue is: Clipping with RAW Photos. It appears Tony's recommendation will only increase the frequency at which RAW Photos are clipped while using Sherloq. The compromise again was intended to avoid bias results.

Again, those images are underexposed or overexposed. The clipping you are showing isn't due to Sherloq. 

Quido mentioned this in the issue you opened previously and asked that examples like this not be provided anymore.

**Comment by JohnConnor01** [comment]
> > Tony, have you checked other sources to see if they corroborate these results? Because we have. And other sources corroborate these very results.
> 
> Yes, I have checked other sources. The 19 images you refer to all have red channels in every imaging app I've tried. To claim they don't is not reasonable.
> 
> If you have information that will help Guido make a decision, I suggest you provide it.


I am happy to provide corroborated results. Given the repeated requests to change software settings and applications in recent history. I am waiting for @GuidoBartoli response on how to publish that information. 
I can provide it publicly or privately. 

Separately. I highlighted how your recommendation will only bring back the very problem (clipping with RAW photos) that you say you are trying to solve.  

Those photos are not being clipped on the current version. But they will be when you apply your recommendation.

**Comment by atadams** [comment]
> Those photos are not being clipped on the current version. But they will be when you apply your recommendation.

They were clipped (I.e., underexposed or overexposed) when the photo was taken. My recommendation would not change that.

**Comment by Ray9T** [comment]
> > Good, then respectfully, let's investigate and not rule images out as a problem.
> > Blaming the software to cause data loss is getting old and shows lack of fundamental understanding of RAW file processing.
> 
> I'll ask again that you stop with the personal attacks.

Where's personal attack in pointing out the fundamental fallacy. Your title says "Data loss" and "clipping", and then you ask for removal of Scaling. 
Do you realize there is 
1. No Data loss
2. Scaling does not bring any data back miraculously. The data is already there in Sherloq when its calling `raw.postprocess`, scaling is not applied as an agreed up on [principle](https://github.com/GuidoBartoli/sherloq/issues/96#issuecomment-2186198728) to provide DATA as close to RAW as possible.  Again,  `No scaling !=Data loss`, and there is no personal attack in this. 

Contrarily, I anticipated a thank you for identifying the fallacy, which I believed would save readers a significant amount of time.
This is a forensic app, and i hope people respect this special purpose application and not turn it into a generic image viewer.

**Comment by atadams** [comment]
> Where's personal attack in pointing out the fundamental fallacy.

When you say the issue is my lack of fundamental understanding, it's personal. And I'll ask you _again_ to stop.

**Comment by Ray9T** [comment]
> > Where's personal attack in pointing out the fundamental fallacy.
> 
> When you say the issue is my lack of fundamental understanding, it's personal. And I'll ask you _again_ to stop.

I understand your perspective, but my intention is simply to show that your concern is not a valid argument. 
If you share your images, i may be able to help you understand if they are real images or VFX.  VFX images often have issues you are pointing out and need specific settings to view them as painted. I'm happy to investigate them for you. 

We can take the discussion/investigation to my repo to avoid digressions.

**Comment by atadams** [comment]
> If you share your images,

**_Again._** This issue isn't about any specific images. It happens with all images.

**Comment by atadams** [comment]
> i may be able to help you understand if they are real images or VFX.

It's not appropriate to be soliciting business on GitHub issues. It might be considered spam.

**Comment by Ray9T** [comment]
> > If you share your images,
> 
> **_Again._** This issue isn't about any specific images. It happens with all images.

The issue you brought up is a non-issue as I pointed out [previously](https://github.com/GuidoBartoli/sherloq/issues/99#issuecomment-2200792868), This only highlights, if I may be, a fundamental misunderstanding. I'm at a loss for how else to express it. 

Whenever I point out a technical misunderstanding in your post, you interpret it as a personal attack, which it is not. Hopefully you see read this in a positive light. 

> It's not appropriate to be soliciting business on GitHub issues. It might be considered spam.
You misunderstood, to rephrase. I meant to avoid spam, i can break down your images for potential anomalies instead of shaping Sherloq to render your image exactly as you desired. 

Use any other image viewer if you dislike gamma (1,1) / no scaling. Is that not an option for you?

**Comment by atadams** [comment]
> You misunderstood and allow me to rephrase. I meant to avoid spam, i can break down your images for potential anomalies instead of shaping Sherloq to render your image exactly as you desired.

Your assumption is I need your help. I don't. Please refrain from any mention of my abilities or skills **_and stick to the issue._ **

**Comment by GuidoBartoli** [comment]
Guys... every time we make a change within the RAW file import a ruckus happens here, you really make me regret leaving this feature inside Sherloq.

Let's make this the last adjustment on this, shall we?

In 4f89cfa6da60f24e2c18ab6a658dcca98f850362 commit, the `postprocess()` function is called with `no_auto_bright=True` and `use_camera_wb=True`.

**Again, please do not spam and pull more discussions out of the hat for their own sake.**

**Comment by Ray9T** [comment]
@GuidoBartoli this is strange, and you accepted that there is data loss with no scaling = true. 
Can you educate me on how this is a fact?
If not, you just turned Sherloq into a regular image viewer. Is this what you really want? considering you said this is your last change!

As an open-source app owner, you want to see both sides, maintain the integrity of the application and changes based on sound technicals. 

With scaling on you invariably introduced noise, so can you please introduce noise removal tools please?

**Comment by BakersTutz** [comment]
Since Sherloq's inception, "no_auto_scale=true" has never been enabled. It was only last week when it was added. He's just going back to the way it's always been, now without auto changing the white balance or brightness of the image. Sounds like he's leaving the image "as shot" from the camera. Sounds good to me.

**Comment by Ray9T** [comment]
> Since Sherloq's inception, "no_auto_scale=true" has never been enabled. It was only last week when it was added. He's just going back to the way it's always been, now without auto changing the white balance or brightness of the image. Sounds like he's leaving the image "as shot" from the camera. Sounds good to me.

You're advocating for version without Tony's changes good!, then we should go back to (auto_bright=True) and leave everything out!

**Comment by GuidoBartoli** [comment]
I simply removed the `no_auto_scale` option, because I didn't realize it would cause [the problems](https://github.com/GuidoBartoli/sherloq/issues/99#issue-2382318333) @atadams pointed out instead (thanks for reporting that).

> Since Sherloq's inception, "no_auto_scale=true" has never been enabled. It was only last week when it was added. He's just going back to the way it's always been, now without auto changing the white balance or brightness of the image. Sounds like he's leaving the image "as shot" from the camera. Sounds good to me.

Yes, that's the point.

As already explained [here](https://github.com/GuidoBartoli/sherloq/issues/96#issuecomment-2186198728), I would again point out that the option to load a RAW file within a forensic analysis program doesn't make much sense (I don't think even commercial products like [Authenticate](https://ampedsoftware.com/authenticate) have it either).
